Added logic to retry connection because the first connect after cloud_sql_proxy creates an emphermal cert fails.
Concretely the attempt will throw this exception:

2022/07/19 14:39:10 New connection for "depmap-gumbo:us-central1:gumbo-cloudsql"
2022/07/19 14:39:10 refreshing ephemeral certificate for instance depmap-gumbo:us-central1:gumbo-cloudsql
2022/07/19 14:39:10 Reading data from depmap-gumbo:us-central1:gumbo-cloudsql had error: remote error: tls: bad certificate
Traceback (most recent call last):
  File "/Users/pmontgom/dev/gumbo-client/try_connect.py", line 2, in <module>
    c = gumbo_client.Client(config_dir="~/.config/gumbo-staging")
  File "/Users/pmontgom/dev/gumbo-client/gumbo_client/client.py", line 198, in __init__
    connection = psycopg2.connect(**kwargs)
  File "/Users/pmontgom/miniconda3/envs/gumbo-client/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5433 failed: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

My theory is there's some race condition where the new cert has been created but the remote isn't aware of it yet. Added some retry on connect logic.